### PR TITLE
:bug: scripts for input-plugin

### LINKED ISSUE #46: Bug: UX Scripts follow wrong pattern
UX patterns seem to be following the exact pattern that validation is following, but that's not how UX Scripts need to be added to the page. Attached is the whiteboarding we did around UX Scripts as a reminder.

UX Scripts take two arguments, `inputs` and `settings`. `inputs` contain `target`, `all`, and `parent`. `target` is the target element, selected, `all` is a list of all inputs in that plugin, selected, and `parent` is the parent selector that wraps the whole input plugin. The `settings` argument is constructed in the same way that `validation` is.

Because UX scripts may do lots of different things, UX Scripts should be added in a way that they run immediately when available; for validation we control the event listener, but for UX Scripts, they need to control the whole thing. Imagine, for instance, a drag and drop image upload plugin. It would need to to hide the input, replace it with the UX Script uploader, and act whenever is needed. Currently, that's not possible.

Path to resolve:

- [x] Add `parent` to UX scripts `inputs`
- [ ] Attach `scripts` immediately instead of on an event listener
- [ ] Remove `on` check for UX scripts for testing
- [ ] Update existing input plugins that provide UX scripts

This will be a breaking change.

User Script Whiteboarding

### PR DESCRIPTION
**Pull request by ayush2k**
---
Resolves #46 

`DCO 1.1 Signed-off-by: {{Ayush Gupta}} <{{ayush2k@gmail.com}}>`

### CODE REVIEW

File: lib/form/js/ux.js [hunk 1]
```diff
@@ -27,13 +27,12 @@
...
     // Run the script
     script = allPlugins[inp.parent.type].scripts[inp.script.function](input, settings);
-
   };
 
   // Add all event listeners
   Object.keys(allInputs).forEach(function (id) {
     if (allInputs[id].hasOwnProperty('script')) {
-      allIDs[id].addEventListener(allInputs[id].script.on, script);
+      script(allIDs[id]);
```
Comment (ayush2k) [inline lib/form/js/ux.js]: @Snugug @scottnath 
calls script for every input.
In checkboxes, it might be redundant to call script for each checkbox.
[https://github.com/punchcard-cms/input-plugin-checkbox/blob/master/index.js](url)

**Comment by scottnath** [comment]
@ayush2k branch out of date.

**Comment by ayush2k** [comment]
@scottnath Updated
